INSERT INTO RATINGS(RATING)
VALUES ('G');
INSERT INTO RATINGS(RATING)
VALUES ('PG');
INSERT INTO RATINGS(RATING)
VALUES ('PG-13');
INSERT INTO RATINGS(RATING)
VALUES ('R');
INSERT INTO RATINGS(RATING)
VALUES ('NC-17');

INSERT INTO GENRES(GENRE)
VALUES ('Комедия');
INSERT INTO GENRES(GENRE)
VALUES ('Драма');
INSERT INTO GENRES(GENRE)
VALUES ('Мультфильм');
INSERT INTO GENRES(GENRE)
VALUES ('Триллер');
INSERT INTO GENRES(GENRE)
VALUES ('Документальный');
INSERT INTO GENRES(GENRE)
VALUES ('Боевик');