MERGE INTO RATINGS (RATING)
    KEY (RATING)
    VALUES ('G');
MERGE INTO RATINGS (RATING)
    KEY (RATING)
    VALUES ('PG');
MERGE INTO RATINGS (RATING)
    KEY (RATING)
    VALUES ('PG-13');
MERGE INTO RATINGS (RATING)
    KEY (RATING)
    VALUES ('R');
MERGE INTO RATINGS (RATING)
    KEY (RATING)
    VALUES ('NC-17');

MERGE INTO GENRES (GENRE)
    KEY (GENRE)
    VALUES ('Комедия');
MERGE INTO GENRES (GENRE)
    KEY (GENRE)
    VALUES ('Драма');
MERGE INTO GENRES (GENRE)
    KEY (GENRE)
    VALUES ('Мультфильм');
MERGE INTO GENRES (GENRE)
    KEY (GENRE)
    VALUES ('Триллер');
MERGE INTO GENRES (GENRE)
    KEY (GENRE)
    VALUES ('Документальный');
MERGE INTO GENRES (GENRE)
    KEY (GENRE)
    VALUES ('Боевик');

MERGE INTO FRIENDSHIP_STATUS (STATUS)
    KEY (STATUS)
    VALUES ('CONFIRMED');
MERGE INTO FRIENDSHIP_STATUS (STATUS)
    KEY (STATUS)
    VALUES ('UNCONFIRMED')